dotfiles: self-bootstrap vim-plug and the zsh plugins

diff --git a/dotfiles/zshrc b/dotfiles/zshrc
--- a/dotfiles/zshrc
+++ b/dotfiles/zshrc
@@ -1,9 +1,28 @@
 if [ -f ~/.zsh/plugins/zsh-defer/zsh-defer.plugin.zsh ]; then
   source ~/.zsh/plugins/zsh-defer/zsh-defer.plugin.zsh
 else
-  echo "zsh-defer is missing! run \`setup.sh\`"
-  echo "you'll get some errors below..."
-  echo
+  # self-bootstrap the plugins on first start
+  if command -v git > /dev/null; then
+    echo "cloning zsh plugins into ~/.zsh/plugins..."
+    mkdir -p ~/.zsh/plugins
+    (
+      cd ~/.zsh/plugins || exit
+      git clone -q https://github.com/mafredri/z -b zsh-flock
+      git clone -q https://github.com/chriskempson/base16-shell
+      git clone -q https://github.com/hlissner/zsh-autopair
+      git clone -q https://github.com/romkatv/gitstatus
+      git clone -q https://github.com/zdharma-continuum/fast-syntax-highlighting
+      git clone -q https://github.com/romkatv/zsh-defer
+    )
+  fi
+
+  if [ -f ~/.zsh/plugins/zsh-defer/zsh-defer.plugin.zsh ]; then
+    source ~/.zsh/plugins/zsh-defer/zsh-defer.plugin.zsh
+  else
+    echo "zsh-defer is missing!"
+    echo "you'll get some errors below..."
+    echo
+  fi
 fi
 
 # load files
